#version 450

layout(local_size_x = 64) in;

struct FirePixel {
    int posX, posY;
    float r, g, b, a;
    float velX, velY;
};

struct GPUEnemy {
    float x, y;
    float pad[2];
};

layout(std430, binding = 0) buffer ParticleBuffer {
    FirePixel particles[];
};

layout(rgba8, binding = 2) uniform image2D outputImage;

layout(std430, binding = 3) buffer EnemyBuffer {
    GPUEnemy enemies[];
};

layout(std430, binding = 4) buffer HitBuffer {
    int hits[];
};

uniform float deltaTime;
uniform int enemyCount;
uniform int ssboOffset;

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= 2034) return;

    uint bufferIndex = uint(ssboOffset) + id;
    FirePixel p = particles[bufferIndex];

    imageStore(outputImage, ivec2(p.posX, p.posY), vec4(0.0));

    p.posX += int(p.velX * deltaTime * 15);
    p.posY += int(p.velY * deltaTime * 15);
    p.a -= deltaTime * 1.5;

    if (p.a <= 0.0) {
        p.a    = 0.0;
        p.velX = 0.0;
        p.velY = 0.0;
        particles[bufferIndex] = p;
        return; 
    }

    
    for (int ei = 0; ei < enemyCount; ei++) {
        float dx = float(p.posX) - enemies[ei].x;
        float dy = float(p.posY) - enemies[ei].y;
        if (dx*dx + dy*dy < 16.0 * 16.0) {
            atomicOr(hits[ei], 1);
        }
    } 
    
    imageStore(outputImage, ivec2(p.posX, p.posY), vec4(p.r, p.g, p.b, p.a));
    particles[bufferIndex] = p;
}
