#version 450

layout(local_size_x = 64) in;

struct WaterParticle {
    int type;
    int life;
    float posX;
    float posY;
    float startX, startY;
    float dirX, dirY;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    WaterParticle particles[];
};

layout(rgba8, binding = 1) uniform image2D outputImage;

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

uniform int particleCount;

void main(){
    uint id = gl_GlobalInvocationID.x;
    if (id >= particleCount) return;

    WaterParticle particle = particles[id];

    for (int dy = -1; dy <= 1; dy++) {
        for (int dx = -1; dx <= 1; dx++) {
            float variation = hash(vec2(dx, dy)) * 60.0 - 30.0;

            vec4 color = vec4(
                0.0,
                clamp(100.0 + variation, 0.0, 255.0) / 255.0,
                clamp(101.0  + variation, 0.0, 255.0) / 255.0,
                1.0
            );

            ivec2 coord = ivec2(int(particle.posX) + dx, int(particle.posY) + dy);
            imageStore(outputImage, coord, color);
        }
    }
}   